version : "3"
services : 
  s1 :
    build : "./service-a"
    ports:
      - "4000:4000"
  s2: 
    build : "./service-b"
    ports:
      - "5000:5000"
  s3 : 
    build : "./service-c"
    ports:
      - "9000:9000"

  nginx :
    image : "nginx:latest"
    ports : 
      - "8080:8080"
    volumes: ["./nginx.conf:/etc/nginx/nginx.conf"]
    depends_on:
      - "s1"
      - "s2"
      - "s3"
    
  